config/routes.rb
EssentialDataDemo::Application.routes.draw do

  root :to => 'articles#index'

  resources :articles do
    resource :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title

  has_many :comments

  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :author, :content

  belongs_to :article

  validates :author, :presence => true
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find_by_id(params[:id])
  end

  def new
    #@article = Article.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      respond_to do |format|
        format.html {render :action => :new}
        format.js {render :action => :new}
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find_by_id(params[:id])
  end

  def new
    @comment = Comment.new
    @article = {id: params[:article_id]}
    respond_to do |format|
      format.js
    end
  end

  def create
    article = Article.find_by_id(params[:article_id])
    @comment = article.comments.build(params[:comment])
    if @comment.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      respond_to do |format|
        format.html {render :action => :new}
        format.js {render :action => :new}
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= form_for Article.new, :html => {:class => "form-horizontal"}, :remote => true do |f|
  .control-group
    = label :article, :title, :class => "control-label"
    .controls
      = text_field :article, :title, :required=>true, :title => 'This field is required'
  .control-group
    = label :article, :content, :class => "control-label"
    .controls
      = text_area :article, :content, :rows => 7, :required=>true, :title => 'This field is required'
  .control-group
    = f.button :class=>"btn btn-primary"
    %button.btn{:"data-dismiss"=>"modal", :'aria-hidden'=>"true"}
      Cancel

app/views/articles/create.js.erb
$('#modal-window').modal('hide');
$('#articles').append('<div class="span12 article"><h2><%= @article.title%></h2><p><%= truncate(@article.content, length: 200) %></p><p><a class="btn" href="<%= article_path(@article)%>">View details »</a></p></div>');
$('#articles .article:last').attr('style','background-color: lightgreen' );
$('body').scrollTo('#articles .article:last',800);
$('#articles .article:last').animate({ backgroundColor: "white" }, 3000);

app/views/articles/index.html.haml
#articles
  - @articles.each do |article|
    .span12.article
      %h2
        = article.title
      %p
        = truncate(article.content, length: 200)
      %p
        %a.btn{:href => article_path(article)}
          View details »

app/views/articles/new.js.erb
//$('.modal-body').html('<%#= escape_javascript(render :partial => 'form', :object => @article) %>');
$('.modal-body').html('<%= escape_javascript(render :partial => 'form') %>');
$('.modal-footer').remove(); // don't need a footer here
$('#modal-window-label').html('Add Article');
//$('.modal-header').remove(); // don't need a header here

app/views/articles/show.html.haml
.span12
  %h2
    = @article.title
  %p
    = @article.content
  %h3
    Comments
    = link_to 'Add Comment', new_article_comments_path(@article), :remote => true, :class => 'btn btn-primary',:style => 'float: right;', 'data-toggle' => 'modal', 'data-target' => "#modal-window", 'data-backdrop' => true, 'data-keyboard' => true

.span10.offset1
  - @article.comments.each do |comment|
    .media
      .media-body
        %h4.media-heading
          = comment.author
        =comment.content

app/views/comments/_form.html.haml
= form_for @comment, as: :comment, url: article_comments_path, :html => {:class => "form-horizontal"}, :remote => true do |f|
  .control-group
    = label :comment, :author, :class => "control-label"
    .controls
      = text_field :comment, :author, :required=>true, :title => 'This field is required'
  .control-group
    = label :comment, :content, :class => "control-label"
    .controls
      = text_area :comment, :content, :rows => 7, :required=>true, :title => 'This field is required'
  .control-group
    = f.button :class=>"btn btn-primary"
    %button.btn{:"data-dismiss"=>"modal", :'aria-hidden'=>"true"}
      Cancel

app/views/comments/create.js.erb
$('#modal-window').modal('hide');
$('.span10.offset1').append('<div class="media"><div class="media-body"><h4 class="media-heading"><%= @comment.author%></h4><%= @comment.content%></div></div>');
$('.span10 .media:last').attr('style','background-color: lightgreen' );
$('body').scrollTo('.span10 .media:last',800);
$('.span10 .media:last').animate({ backgroundColor: "white" }, 3000);

app/views/comments/new.js.erb
$('.modal-body').html('<%= escape_javascript(render :partial => 'form', :object => @comment, :locals => {:article => @article}) %>');
$('.modal-footer').remove(); // don't need a footer here
$('#modal-window-label').html('Add Comment');
//$('.modal-header').remove(); // don't need a header here

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %title
      EssentialDataDemo

    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    -#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

    = javascript_include_tag "application"
    = javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.js"
    = javascript_include_tag "http://demos.flesler.com/jquery/scrollTo/js/jquery.scrollTo-min.js"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand(href=root_path)
            EssentialDataDemo
          .container
            %ul.nav.nav-pills
              %li
                = link_to 'Add Article', new_article_path, :remote => true, 'data-toggle' => 'modal', 'data-target' => "#modal-window", 'data-backdrop' => true, 'data-keyboard' => true
              %li
                = link_to 'All Articles', root_path
    .container
      .row
        = yield

%div{:id=>"modal-window", :class=>"modal hide", :tabindex=>"-1", :role=>"dialog", :'aria-labelledby'=>"myModalLabel", :'aria-hidden'=>"false"}
  .modal-header
    %button{:type=>"button", :class=>"close", :'data-dismiss'=>"modal", :'aria-hidden'=>"true"}
      ×
    %h3#modal-window-label

  .modal-body
  .modal-footer
    &nbsp;